### ISSUE TITLE
Add schema-b templates for `ec2_logs`, `ec2_metrics`, `billing` and `sqs` data streams from AWS package

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-integration-corpus-generator-tool#53]
This issue tracks our first iteration.

The goal is to provide schema-b templates to generate data for 4 data streams in AWS package.

```[tasklist]
- [x] Add `aws.ec2_logs` schema-b template #65
- [x] Add `aws.ec2_metrics` schema-b template #54
- [x] Add `aws.billing` schema-b template #43
- [x] Add `aws.sqs` schema-b template #47
```

**Comment by endorama** [comment]
https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/43

**Comment by endorama** [comment]
`aws.ec2_metrics`: https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/54

**Comment by endorama** [comment]
`aws.ec2_logs`: https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/65

**Comment by endorama** [comment]
All done!
